/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.50
 * Generated at: 2021-08-19 08:57:33 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class loginForm_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(8);
    _jspx_dependants.put("jar:file:/C:/workspace/ThanksTay/ThanksTay/src/main/webapp/wtpwebapps/ThanksTay/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("jar:file:/C:/workspace/ThanksTay/ThanksTay/src/main/webapp/wtpwebapps/ThanksTay/WEB-INF/lib/spring-webmvc-5.2.16.RELEASE.jar!/META-INF/spring.tld", Long.valueOf(1626216726000L));
    _jspx_dependants.put("jar:file:/C:/workspace/ThanksTay/ThanksTay/src/main/webapp/wtpwebapps/ThanksTay/WEB-INF/lib/spring-webmvc-5.2.16.RELEASE.jar!/META-INF/spring-form.tld", Long.valueOf(1626216726000L));
    _jspx_dependants.put("jar:file:/C:/workspace/ThanksTay/ThanksTay/src/main/webapp/wtpwebapps/ThanksTay/WEB-INF/lib/jstl-1.2.jar!/META-INF/fmt.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("/WEB-INF/views/common/tags.jsp", Long.valueOf(1627433983050L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1629344132335L));
    _jspx_dependants.put("jar:file:/C:/workspace/ThanksTay/ThanksTay/src/main/webapp/wtpwebapps/ThanksTay/WEB-INF/lib/jstl-1.2.jar!/META-INF/fn.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("/WEB-INF/lib/spring-webmvc-5.2.16.RELEASE.jar", Long.valueOf(1629348439233L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<style>\r\n");
      out.write("    .modal-lg {\r\n");
      out.write("      max-width: 630px !important;\r\n");
      out.write("    }\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("<!-- Button trigger modal -->\r\n");
      out.write("<button type=\"button\" class=\"btn btn-primary\" data-bs-toggle=\"modal\" data-bs-target=\"#loginRegisterModal\">Launch demo modal\r\n");
      out.write("</button>\r\n");
      out.write("\r\n");
      out.write("<!---------------------------------------------- 로그인 또는 회원가입 ------------------------------------------------------->\r\n");
      out.write("<div class=\"modal fade\" id=\"loginRegisterModal\" tabindex=\"-1\" aria-labelledby=\"loginRegisterModal\" aria-hidden=\"true\">\r\n");
      out.write("    <div class=\"modal-dialog modal-lg modal-dialog-centered modal-dialog-scrollable\">\r\n");
      out.write("        <div class=\"modal-content\">\r\n");
      out.write("            <div class=\"row modal-header d-flex justify-content-between\">\r\n");
      out.write("                <div class=\"col-4\">\r\n");
      out.write("                    <button type=\"button\" style=\"float: left;\" class=\"btn-close\" data-bs-dismiss=\"modal\" aria-label=\"Close\"></button>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"col-4\">\r\n");
      out.write("                    <p class=\"modal-title text-center\" id=\"loginRegisterModalLabel\" style=\"font-size: 1.1em\"><strong>로그인 또는 회원가입</strong></p>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"col-4\">\r\n");
      out.write("                    &nbsp;\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"modal-body container mt-3\">\r\n");
      out.write("                <h3 class=\"pb-3\"><strong>Thxty에 오신 것을 환영합니다.</strong></h3>\r\n");
      out.write("                <div class=\"form-floating my-3\">\r\n");
      out.write("                    <input type=\"email\" class=\"form-control\" id=\"loginEmail\" name=\"email\">\r\n");
      out.write("                    <label for=\"loginEmail\">이메일</label>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"d-grid gap-2\">\r\n");
      out.write("                    <button type=\"button\" class=\"btn btn-danger btn-lg\" id=\"btn-emailCheck\">계속</button>\r\n");
      out.write("                </div>\r\n");
      out.write("                <hr>\r\n");
      out.write("                <div class=\"d-grid gap-2\">\r\n");
      out.write("                  <button type=\"button\" class=\"btn btn-lg my-2\" style=\"background-color:white !important; border: 1px solid black !important;\">페이스북으로 로그인하기</button>\r\n");
      out.write("                  <button type=\"button\" id=\"kakaoLogout\" class=\"btn btn-lg my-2\" style=\"background-color:white !important; border: 1px solid black !important;\">구글로 로그인하기</button>\r\n");
      out.write("                  <button type=\"button\" id=\"kakaoLogin\" class=\"btn btn-lg my-2\" style=\"background-color:white !important; border: 1px solid black !important;\">\r\n");
      out.write("                      <div class=\"row\">\r\n");
      out.write("                          <div class=\"col-1\">\r\n");
      out.write("                              <img src=\"resources/images/kakaoLogo.png\" style=\"width:30px; height:30px;\">\r\n");
      out.write("                          </div>\r\n");
      out.write("                          <div class=\"col-11 text-center\">카카오로 로그인하기</div>\r\n");
      out.write("                      </div>\r\n");
      out.write("                  </button>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<!---------------------------------------------- 로그인 ------------------------------------------------------->\r\n");
      out.write("<div class=\"modal fade\" id=\"loginModal\" aria-hidden=\"true\" aria-labelledby=\"loginModal\" tabindex=\"-1\">\r\n");
      out.write("    <div class=\"modal-dialog modal-lg modal-dialog-centered modal-dialog-scrollable\">\r\n");
      out.write("        <div class=\"modal-content\">\r\n");
      out.write("            <div class=\"row modal-header d-flex justify-content-between\">\r\n");
      out.write("                <div class=\"col-4\">\r\n");
      out.write("                  <i class=\"fas fa-chevron-left\" style=\"float: left;\" data-bs-target=\"#loginRegisterModal\" data-bs-toggle=\"modal\" data-bs-dismiss=\"modal\"></i>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"col-4\">\r\n");
      out.write("                    <p class=\"modal-title text-center\" id=\"loginModalLabel\" style=\"font-size: 1.1em;\"><strong>로그인</strong></p>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"col-4\">\r\n");
      out.write("                    &nbsp;\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"modal-body\">\r\n");
      out.write("                <div class=\"form-floating mb-3\">\r\n");
      out.write("                    <input type=\"password\" class=\"form-control\" id=\"password\" placeholder=\"******\" name=\"password\">\r\n");
      out.write("                    <label for=\"password\">비밀번호</label>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"d-grid gap-2\">\r\n");
      out.write("                    <button type=\"button\" class=\"btn btn-danger btn-lg\" style=\"font-size: 1.1em;\" id=\"btn-login\">로그인</button>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <div class=\"pt-3\">\r\n");
      out.write("                    <a><strong>비밀번호를 잊으셨나요?</strong></a>\r\n");
      out.write("                    <p>&nbsp;</p>\r\n");
      out.write("                    <p>&nbsp;</p>\r\n");
      out.write("                    <p>&nbsp;</p>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<!---------------------------------------------- 회원가입 완료하기 ------------------------------------------------------->\r\n");
      out.write("<div class=\"modal fade\" id=\"registerModal\" aria-hidden=\"true\" aria-labelledby=\"registerModal\" tabindex=\"-1\">\r\n");
      out.write("    <div class=\"modal-dialog modal-lg modal-dialog-centered modal-dialog-scrollable\">\r\n");
      out.write("        <div class=\"modal-content\">\r\n");
      out.write("            <div class=\"row modal-header d-flex justify-content-between\">\r\n");
      out.write("                <div class=\"col-4\">\r\n");
      out.write("                    <i class=\"fas fa-chevron-left\" style=\"float: left;\" data-bs-target=\"#loginRegisterModal\" data-bs-toggle=\"modal\" data-bs-dismiss=\"modal\"></i>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"col-4\">\r\n");
      out.write("                    <p class=\"modal-title text-center\" id=\"registerModalLabel\" style=\"font-size: 1.1em;\"><strong>회원가입 완료하기</strong></p>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"col-4\">\r\n");
      out.write("                    &nbsp;\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"modal-body\">\r\n");
      out.write("                <div class=\"form-floating\">\r\n");
      out.write("                    <input type=\"text\" class=\"form-control\" id=\"LastName\" placeholder=\"이름(예:길동)\">\r\n");
      out.write("                    <label for=\"LastName\">이름(예:길동)</label>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"form-floating mb-3\">\r\n");
      out.write("                    <input type=\"text\" class=\"form-control\" id=\"FirstName\" placeholder=\"이름(예:홍)\">\r\n");
      out.write("                    <label for=\"FirstName\">성(예:홍)</label>\r\n");
      out.write("                    <p style=\"color: gray; font-size: small\" class=\"pt-1\">정부 발급 신분증에 표시된 이름과 일치하는지 확인하세요.</p>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"form-floating mb-3\">\r\n");
      out.write("                    <input type=\"date\" class=\"form-control\" id=\"RegisterBirth\" placeholder=\"2012.12.12\">\r\n");
      out.write("                    <label for=\"RegisterBirth\">생년월일</label>\r\n");
      out.write("                    <p style=\"color: gray; font-size: small\" class=\"pt-1\">만 18세 이상의 성인만 회원으로 가입할 수 있습니다.</p>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"form-floating mb-3\">\r\n");
      out.write("                    <input type=\"text\" class=\"form-control\" id=\"RegisterPhone\" placeholder=\"010-1234-5678\">\r\n");
      out.write("                    <label for=\"RegisterBirth\">전화번호</label>\r\n");
      out.write("                    <p style=\"color: gray; font-size: small\" class=\"pt-1\">전화번호는 호스트나 게스트, 또는 에어비앤비에서 연락을 취하기 위해 필요합니다.</p>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"form-floating mb-3\">\r\n");
      out.write("                    <input type=\"email\" class=\"form-control\" id=\"RegisterEmail\" placeholder=\"hong@naver.com\" readonly>\r\n");
      out.write("                    <label for=\"RegisterEmail\">이메일</label>\r\n");
      out.write("                    <p style=\"color: gray; font-size: small\" class=\"pt-1\">예약 확인과 영수증을 이메일로 보내드립니다.</p>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"form-floating mb-3\">\r\n");
      out.write("                    <input type=\"password\" class=\"form-control\" id=\"RegisterPassword\" placeholder=\"******\">\r\n");
      out.write("                    <label for=\"RegisterPassword\">비밀번호</label>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div>\r\n");
      out.write("                    <p style=\"font-size: small\">\r\n");
      out.write("                        아래의 <strong>동의 및 계속하기</strong> 버튼을 선택하면, Thxtay의\r\n");
      out.write("                        <strong>\r\n");
      out.write("                            <a href=\"https://www.airbnb.co.kr/help/article/2908/%EC%9D%B4%EC%9A%A9%EC%95%BD%EA%B4%80\" target=\"_blank\">서비스 약관</a>,\r\n");
      out.write("                            <a href=\"https://www.airbnb.co.kr/help/article/2909/%EA%B2%B0%EC%A0%9C-%EC%84%9C%EB%B9%84%EC%8A%A4-%EC%95%BD%EA%B4%80\" target=\"_blank\">결제 서비스 약관</a>,\r\n");
      out.write("                            <a href=\"https://www.airbnb.co.kr/help/article/2855/%EA%B0%9C%EC%9D%B8%EC%A0%95%EB%B3%B4-%EC%B2%98%EB%A6%AC%EB%B0%A9%EC%B9%A8\" target=\"_blank\">개인정보 처리방침</a>,\r\n");
      out.write("                            <a href=\"https://www.airbnb.co.kr/help/article/2867/%EC%B0%A8%EB%B3%84-%EA%B8%88%EC%A7%80-%EC%A0%95%EC%B1%85\" target=\"_blank\">차별 금지 정책</a>\r\n");
      out.write("                        </strong> 에 동의하는 것입니다.\r\n");
      out.write("                    </p>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"d-grid gap-2\">\r\n");
      out.write("                    <button type=\"button\" class=\"btn btn-danger btn-lg\" id=\"btn-register\">동의 및 계속하기</button>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<!---------------------------------------------- Thxtay 커뮤니티 가입하기 ------------------------------------------------------->\r\n");
      out.write("<div class=\"modal fade\" id=\"registerModal2\" aria-hidden=\"true\" aria-labelledby=\"registerModal2\" tabindex=\"-1\">\r\n");
      out.write("    <div class=\"modal-dialog modal-lg modal-dialog-centered modal-dialog-scrollable\">\r\n");
      out.write("        <div class=\"modal-content\">\r\n");
      out.write("            <div class=\"row modal-header d-flex justify-content-center\">\r\n");
      out.write("                <div class=\"col-12\">\r\n");
      out.write("                    <p class=\"modal-title text-center\" id=\"registerModalLabel2\" style=\"font-size: 1.1em;\"><strong>Thxtay 커뮤니티 완료하기</strong></p>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"modal-body\">\r\n");
      out.write("                <h3 class=\"py-3\">Thxaty는 누구나 어디에서나 우리 집처럼 편안함을 느낄 수 있는 커뮤니티입니다.</h3>\r\n");
      out.write("                <p class=\"pb-3\">이를 위해 Thxtay는 다음에 동의해 주실 것을 부탁드립니다.</p>\r\n");
      out.write("\r\n");
      out.write("                <p><strong>Thxtay 커뮤니티를 위한 약속</strong></p>\r\n");
      out.write("                <p>모든 Thxtay 커뮤니티 회원을 인종, 종교, 출신 국가, 민족, 피부색, 장애, 성별, 성적 정체성, 성적 취향 또는 연령에 상관없이 존중하며 개인적 판단이나 편견 없이 대하겠습니다. <strong>자세히 알아보기</strong></p>\r\n");
      out.write("\r\n");
      out.write("                <hr>\r\n");
      out.write("                <div class=\"d-grid gap-2 mb-3\">\r\n");
      out.write("                    <button type=\"button\" class=\"btn btn-danger btn-lg\" data-bs-target=\"#addProfile\" data-bs-toggle=\"modal\" data-bs-dismiss=\"modal\">동의 및 계속하기</button>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"d-grid gap-2\">\r\n");
      out.write("                    <button type=\"button\" class=\"btn btn-lg\" style=\"background-color:white !important; border: 1px solid black !important;\">거절하기</button>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<!---------------------------------------------- 프로필 생성하기 ------------------------------------------------------->\r\n");
      out.write("<div class=\"modal fade\" id=\"addProfile\" aria-hidden=\"true\" aria-labelledby=\"addProfile\" tabindex=\"-1\">\r\n");
      out.write("    <div class=\"modal-dialog modal-lg modal-dialog-centered modal-dialog-scrollable\">\r\n");
      out.write("        <div class=\"modal-content\">\r\n");
      out.write("            <div class=\"row modal-header d-flex justify-content-between\">\r\n");
      out.write("                <div class=\"col-4\">\r\n");
      out.write("                    <button type=\"button\" style=\"float: left;\" class=\"btn-close\" data-bs-dismiss=\"modal\" aria-label=\"Close\"></button>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"col-4\">\r\n");
      out.write("                    <p class=\"modal-title text-center\" id=\"addProfileLabel\" style=\"font-size: 1.1em\"><strong>프로필 생성하기</strong></p>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"col-4\">\r\n");
      out.write("                    &nbsp;\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"modal-body\">\r\n");
      out.write("                <div class=\"d-flex justify-content-center\">\r\n");
      out.write("                    <p style=\"font-family: 'Lobster', cursive; font-size:40px; text-decoration-line: none; color: #FF5555;\">Thxtay</p>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"text-center\">\r\n");
      out.write("                    <h3><strong>Thxtay에 오신 것을 환영합니다</strong></h3>\r\n");
      out.write("                    <p>전 세계 숙소, 현지 레스토랑 및 독특한 체험을 찾아보세요.</p>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"d-grid gap-2 py-2\">\r\n");
      out.write("                    <button type=\"button\" class=\"btn btn-dark btn-lg\" data-bs-target=\"#addProfileImg\" data-bs-toggle=\"modal\" data-bs-dismiss=\"modal\">계속</button>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<!---------------------------------------------- 프로필 생성하기2 ------------------------------------------------------->\r\n");
      out.write("<div class=\"modal fade\" id=\"addProfileImg\" aria-hidden=\"true\" aria-labelledby=\"addProfileImg\" tabindex=\"-1\">\r\n");
      out.write("    <div class=\"modal-dialog modal-lg modal-dialog-centered modal-dialog-scrollable\">\r\n");
      out.write("        <div class=\"modal-content\">\r\n");
      out.write("            <div class=\"row modal-header d-flex justify-content-between\">\r\n");
      out.write("                <div class=\"col-4\">\r\n");
      out.write("                    <i class=\"fas fa-chevron-left\" style=\"float: left;\" data-bs-target=\"#addProfile\" data-bs-toggle=\"modal\" data-bs-dismiss=\"modal\"></i>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"col-4\">\r\n");
      out.write("                    <p class=\"modal-title text-center\" id=\"addProfileImgLabel\" style=\"font-size: 1.1em\"><strong>프로필 생성하기</strong></p>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"col-4\">\r\n");
      out.write("                    &nbsp;\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"modal-body\">\r\n");
      out.write("                <div class=\"d-flex justify-content-center\">\r\n");
      out.write("                    <h4><strong>프로필 사진 추가</strong></h4>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"text-center\">\r\n");
      out.write("                    <p>얼굴이 보이는 이미지를 선택하세요. 호스트는 예약이 확정된 후에만 사진을 볼 수 있습니다.</p>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"d-flex justify-content-center\">\r\n");
      out.write("                    <img src=\"resources/images/defaultProfile.jpg\" style=\"display: block; height: 185px; width: 185px; border-radius: 100px;\" id=\"preview-image\"/>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"d-grid gap-2 py-2\">\r\n");
      out.write("                    <button type=\"button\" class=\"btn btn-dark btn-lg\" id=\"btn-upload\">사진 업로드하기</button>\r\n");
      out.write("                    <input type=\"file\" id=\"input-image\" style=\"display: none;\"/>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"d-grid gap-2\">\r\n");
      out.write("                    <button type=\"button\" class=\"btn btn-lg my-2\" style=\"background-color:white !important; border: 1px solid black !important;\" id=\"btn-complete\">완료</button>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</div>\r\n");
      out.write("<script src=\"https://developers.kakao.com/sdk/js/kakao.min.js\"></script>\r\n");
      out.write("<script>\r\n");
      out.write("    $(function () {\r\n");
      out.write("        var emailModal = new bootstrap.Modal(document.getElementById(\"loginRegisterModal\"));\r\n");
      out.write("        var passwordModal = new bootstrap.Modal(document.getElementById(\"loginModal\"));\r\n");
      out.write("        var registerModal = new bootstrap.Modal(document.getElementById(\"registerModal\"));\r\n");
      out.write("        var registerModal2 = new bootstrap.Modal(document.getElementById(\"registerModal2\"));\r\n");
      out.write("        var profileImgModal = new bootstrap.Modal(document.getElementById(\"addProfileImg\"));\r\n");
      out.write("\r\n");
      out.write("        function CheckEmail(str) {\r\n");
      out.write("            var reg_email = /^([0-9a-zA-Z_\\.-]+)@([0-9a-zA-Z_-]+)(\\.[0-9a-zA-Z_-]+){1,2}$/;\r\n");
      out.write("            if (!reg_email.test(str)) {\r\n");
      out.write("                return false;\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            return true;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        function CheckAge(age) {\r\n");
      out.write("            var d = new Date(age.split(\"/\").reverse().join(\"-\"));\r\n");
      out.write("            var dd = d.getDate();\r\n");
      out.write("            var mm = d.getMonth()+1;\r\n");
      out.write("            var yy = d.getFullYear();\r\n");
      out.write("            var age_date = yy + \"/\" + mm + \"/\" + dd;\r\n");
      out.write("            var birthDate = new Date(age_date);\r\n");
      out.write("            var cur = new Date();\r\n");
      out.write("            var diff = cur - birthDate;\r\n");
      out.write("            var age = Math.floor(diff/31536000000);\r\n");
      out.write("            if (age >= 18) {\r\n");
      out.write("                return true;\r\n");
      out.write("            } else {\r\n");
      out.write("                return false;\r\n");
      out.write("            }\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        $('#btn-emailCheck').click(function () {\r\n");
      out.write("            var checkEmail = $.trim($('#loginEmail').val());\r\n");
      out.write("            if (!checkEmail) {\r\n");
      out.write("                alertify.alert(\"이메일은 필수 입력값 입니다.\")\r\n");
      out.write("                $('#loginEmail').focus();\r\n");
      out.write("\r\n");
      out.write("                return false;\r\n");
      out.write("            } else {\r\n");
      out.write("                if(!CheckEmail(checkEmail)) {\r\n");
      out.write("                    alertify.alert(\"이메일 형식이 잘못되었습니다.\");\r\n");
      out.write("                    $('#loginEmail').focus();\r\n");
      out.write("\r\n");
      out.write("                    return false;\r\n");
      out.write("                }\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            $('#RegisterEmail').val(checkEmail);\r\n");
      out.write("\r\n");
      out.write("            $.ajax({\r\n");
      out.write("                url:\"/emailCheck\",\r\n");
      out.write("                dataType: 'json',\r\n");
      out.write("                data:{email: checkEmail},\r\n");
      out.write("                success:function (retVal) {\r\n");
      out.write("                    if (retVal.res === \"OK\") {\r\n");
      out.write("                        passwordModal.show();\r\n");
      out.write("                    } else if(retVal.res === \"FAIL\") {\r\n");
      out.write("                        registerModal.show();\r\n");
      out.write("                    }\r\n");
      out.write("                    emailModal.hide();\r\n");
      out.write("                },\r\n");
      out.write("                error : function (request, status, error) {\r\n");
      out.write("                    alertify.alert(\"code:\"+request.status+\"\\n\"+\"message:\"+request.responseText+\"\\n\"+\"error:\"+error);\r\n");
      out.write("                }\r\n");
      out.write("            })\r\n");
      out.write("\r\n");
      out.write("            return true;\r\n");
      out.write("        })\r\n");
      out.write("\r\n");
      out.write("        $('#btn-login').click(function () {\r\n");
      out.write("            var email = $.trim($('#loginEmail').val());\r\n");
      out.write("            var password = $.trim($('#password').val());\r\n");
      out.write("\r\n");
      out.write("            if (!password) {\r\n");
      out.write("                alertify.alert(\"비밀번호를 입력해주세요.\")\r\n");
      out.write("                $('#password').focus();\r\n");
      out.write("\r\n");
      out.write("                return false;\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            $.ajax({\r\n");
      out.write("                url:\"/login2\",\r\n");
      out.write("                dataType: 'json',\r\n");
      out.write("                method: 'post',\r\n");
      out.write("                data:{email: email, password: password},\r\n");
      out.write("                success:function (retVal) {\r\n");
      out.write("                    if (retVal.res === \"OK\") {\r\n");
      out.write("                        passwordModal.hide();\r\n");
      out.write("                    } else if (retVal.res === \"FAIL\") {\r\n");
      out.write("                        alertify.alert(\"비밀번호가 맞지 않습니다.\");\r\n");
      out.write("                        $('#password').val(\"\").focus();\r\n");
      out.write("\r\n");
      out.write("                        return false;\r\n");
      out.write("                    }\r\n");
      out.write("                },\r\n");
      out.write("                error : function (request, status, error) {\r\n");
      out.write("                    alertify.alert(\"code:\"+request.status+\"\\n\"+\"message:\"+request.responseText+\"\\n\"+\"error:\"+error);\r\n");
      out.write("                }\r\n");
      out.write("            })\r\n");
      out.write("\r\n");
      out.write("            return true;\r\n");
      out.write("        })\r\n");
      out.write("\r\n");
      out.write("        $('#btn-register').click(function () {\r\n");
      out.write("            var lastName = $.trim($('#LastName').val());\r\n");
      out.write("            var firstName = $.trim($('#FirstName').val());\r\n");
      out.write("            var name = firstName + lastName;\r\n");
      out.write("            var birth = $.trim($('#RegisterBirth').val());\r\n");
      out.write("            var phone = $.trim($('#RegisterPhone').val());\r\n");
      out.write("            var email = $.trim($('#RegisterEmail').val());\r\n");
      out.write("            var password = $.trim($('#RegisterPassword').val());\r\n");
      out.write("\r\n");
      out.write("            if (!lastName) {\r\n");
      out.write("                alertify.alert(\"이름을 입력해주세요.\")\r\n");
      out.write("                $('#lastName').focus();\r\n");
      out.write("\r\n");
      out.write("                return false;\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            if (!firstName) {\r\n");
      out.write("                alertify.alert(\"성을 입력해주세요.\")\r\n");
      out.write("                $('#FirstName').focus();\r\n");
      out.write("\r\n");
      out.write("                return false;\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            if (!birth) {\r\n");
      out.write("                alertify.alert(\"생년월일을 입력해주세요.\")\r\n");
      out.write("                $('#RegisterBirth').focus();\r\n");
      out.write("\r\n");
      out.write("                return false;\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            if (!phone) {\r\n");
      out.write("                alertify.alert(\"전화번호를 입력해주세요.\")\r\n");
      out.write("                $('#RegisterPhone').focus();\r\n");
      out.write("\r\n");
      out.write("                return false;\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            if (!password) {\r\n");
      out.write("                alertify.alert(\"비밀번호를 입력해주세요.\")\r\n");
      out.write("                $('#RegisterPassword').focus();\r\n");
      out.write("\r\n");
      out.write("                return false;\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("            if (CheckAge(birth) == false) {\r\n");
      out.write("                alertify.alert(\"만 18세 미만은 가입을 할 수 없습니다.\");\r\n");
      out.write("\r\n");
      out.write("                return false;\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("            $.ajax({\r\n");
      out.write("                url:\"/register\",\r\n");
      out.write("                dataType: 'json',\r\n");
      out.write("                method: 'post',\r\n");
      out.write("                data:{\r\n");
      out.write("                    name: name,\r\n");
      out.write("                    birth: birth,\r\n");
      out.write("                    phone: phone,\r\n");
      out.write("                    email: email,\r\n");
      out.write("                    password: password\r\n");
      out.write("                },\r\n");
      out.write("                success:function (retVal) {\r\n");
      out.write("                    if (retVal.res === \"OK\") {\r\n");
      out.write("                        alertify.alert('회원가입 성공');\r\n");
      out.write("                        registerModal2.show();\r\n");
      out.write("                    }\r\n");
      out.write("\r\n");
      out.write("                    registerModal.hide();\r\n");
      out.write("                },\r\n");
      out.write("                error : function () {\r\n");
      out.write("                    alertify.alert('ajax통신 실패!!!!');\r\n");
      out.write("                }\r\n");
      out.write("            })\r\n");
      out.write("\r\n");
      out.write("            return true;\r\n");
      out.write("        })\r\n");
      out.write("\r\n");
      out.write("        // 버튼을 클릭하면\r\n");
      out.write("        $('#btn-upload').click(function (e) {\r\n");
      out.write("            e.preventDefault();\r\n");
      out.write("            // input file 타입이 실행됨\r\n");
      out.write("            $('#input-image').click();\r\n");
      out.write("        })\r\n");
      out.write("\r\n");
      out.write("        $('#btn-complete').click(function() {\r\n");
      out.write("            var formData = new FormData();\r\n");
      out.write("            formData.append(\"picture\", $(\"#input-image\")[0].files[0]);\r\n");
      out.write("            formData.append(\"email\", $.trim($('#loginEmail').val()));\r\n");
      out.write("            /* key 확인하기 */\r\n");
      out.write("            for (let key of formData.keys()) {\r\n");
      out.write("                console.log(key);\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            /* value 확인하기 */\r\n");
      out.write("            for (let value of formData.values()) {\r\n");
      out.write("                console.log(value);\r\n");
      out.write("            }\r\n");
      out.write("            jQuery.ajax({\r\n");
      out.write("                url : \"/img\",\r\n");
      out.write("                type : \"POST\",\r\n");
      out.write("                enctype: 'multipart/form-data',\r\n");
      out.write("                dataType : 'json',\r\n");
      out.write("                processData : false,\r\n");
      out.write("                contentType : false,\r\n");
      out.write("                data : formData,\r\n");
      out.write("                success:function(retVal) {\r\n");
      out.write("                    if (retVal.res === \"OK\") {\r\n");
      out.write("                        alertify.alert(\"성공하였습니다.\");\r\n");
      out.write("                        profileImgModal.hide();\r\n");
      out.write("                    }\r\n");
      out.write("                },\r\n");
      out.write("                error: function (jqXHR)\r\n");
      out.write("                {\r\n");
      out.write("                    alertify.alert(jqXHR.responseText);\r\n");
      out.write("                }\r\n");
      out.write("            });\r\n");
      out.write("        })\r\n");
      out.write("\r\n");
      out.write("        Kakao.init('13a6b02c06860d591edf918abaed6fea'); // 발급받은 javascript 키를 사용\r\n");
      out.write("        console.log(Kakao.isInitialized()); // sdk초기화 여부 판단\r\n");
      out.write("\r\n");
      out.write("        // 카카오 로그인\r\n");
      out.write("        $('#kakaoLogin').click(function() {\r\n");
      out.write("            Kakao.Auth.login({\r\n");
      out.write("                success: function() {\r\n");
      out.write("                    Kakao.API.request({\r\n");
      out.write("                        url: '/v2/user/me',\r\n");
      out.write("                        success: res => {\r\n");
      out.write("                            const email = res.kakao_account.email;\r\n");
      out.write("                            const picture = res.properties.profile_image;\r\n");
      out.write("                            const name = res.properties.nickname;\r\n");
      out.write("\r\n");
      out.write("                            const birthday = res.kakao_account.birthday;\r\n");
      out.write("                            // 카카오에서 받아오는 나이는 출생년도는 테스트용으론 불가하고, 연령대만 받아올 수 있어서 가정을 둔다.\r\n");
      out.write("                            const ageRange = res.kakao_account.age_range;\r\n");
      out.write("                            var age = ageRange.substring(0,2);\r\n");
      out.write("\r\n");
      out.write("                            const getBirth = a => {\r\n");
      out.write("                                const date = new Date();\r\n");
      out.write("                                return date.getFullYear() - a + 1; // 올해 - 나이 + 1\r\n");
      out.write("                            }\r\n");
      out.write("\r\n");
      out.write("                            var birth = getBirth(age) + \"-\" + birthday.substr(0,2) + \"-\" + birthday.substr(2,4);\r\n");
      out.write("\r\n");
      out.write("                            $.ajax({\r\n");
      out.write("                                url:\"/registerKakao\",\r\n");
      out.write("                                dataType: 'json',\r\n");
      out.write("                                method: 'post',\r\n");
      out.write("                                data:{\r\n");
      out.write("                                    name: name,\r\n");
      out.write("                                    birth: birth,\r\n");
      out.write("                                    email: email,\r\n");
      out.write("                                    picture: picture\r\n");
      out.write("                                },\r\n");
      out.write("                                success:function (retVal) {\r\n");
      out.write("                                    if (retVal.res === \"OK\") {\r\n");
      out.write("                                        alertify.alert('로그인&회원가입 성공');\r\n");
      out.write("                                    }\r\n");
      out.write("                                    emailModal.hide();\r\n");
      out.write("                                },\r\n");
      out.write("                                error : function () {\r\n");
      out.write("                                    alertify.alert('ajax통신 실패!!!!!!');\r\n");
      out.write("                                }\r\n");
      out.write("                            })\r\n");
      out.write("                        },\r\n");
      out.write("                        fail: function(error) {\r\n");
      out.write("                            console.log(\"로그인은 성공했지만, request user informations : \" +  JSON.stringify(error));\r\n");
      out.write("                        }\r\n");
      out.write("                    })\r\n");
      out.write("                },\r\n");
      out.write("                fail: function(error) {\r\n");
      out.write("                    console.log(\"failed to login: \" + JSON.stringify(error));\r\n");
      out.write("                }\r\n");
      out.write("            })\r\n");
      out.write("        })\r\n");
      out.write("\r\n");
      out.write("        //카카오로그아웃\r\n");
      out.write("        $('#kakaoLogout').click(function() {\r\n");
      out.write("            if (Kakao.Auth.getAccessToken()) {\r\n");
      out.write("                Kakao.API.request({\r\n");
      out.write("                    url: '/v1/user/unlink',\r\n");
      out.write("                    success: function (response) {\r\n");
      out.write("                        console.log(response)\r\n");
      out.write("                    },\r\n");
      out.write("                    fail: function (error) {\r\n");
      out.write("                        console.log(error)\r\n");
      out.write("                    },\r\n");
      out.write("                })\r\n");
      out.write("                Kakao.Auth.setAccessToken(undefined)\r\n");
      out.write("            }\r\n");
      out.write("        })\r\n");
      out.write("    })\r\n");
      out.write("\r\n");
      out.write("    //이미지 미리보기\r\n");
      out.write("    var sel_file;\r\n");
      out.write("\r\n");
      out.write("    $(document).ready(function() {\r\n");
      out.write("        $(\"#input-image\").on(\"change\", handleImgFileSelect);\r\n");
      out.write("    });\r\n");
      out.write("\r\n");
      out.write("    function handleImgFileSelect(e) {\r\n");
      out.write("        var files = e.target.files;\r\n");
      out.write("        var filesArr = Array.prototype.slice.call(files);\r\n");
      out.write("\r\n");
      out.write("        var reg = /(.*?)\\/(jpg|jpeg|png|bmp)$/;\r\n");
      out.write("\r\n");
      out.write("        filesArr.forEach(function(f) {\r\n");
      out.write("            if (!f.type.match(reg)) {\r\n");
      out.write("                alertify.alert(\"확장자는 이미지 확장자만 가능합니다.\");\r\n");
      out.write("                return false;\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            sel_file = f;\r\n");
      out.write("\r\n");
      out.write("            var reader = new FileReader();\r\n");
      out.write("            reader.onload = function(e) {\r\n");
      out.write("                $(\"#preview-image\").attr(\"src\", e.target.result);\r\n");
      out.write("            }\r\n");
      out.write("            reader.readAsDataURL(f);\r\n");
      out.write("        });\r\n");
      out.write("    }\r\n");
      out.write("</script>\r\n");
      out.write("<script>\r\n");
      out.write("    $(document).on(\"keyup\", \"#RegisterPhone\", function() {\r\n");
      out.write("        $(this).val( $(this).val().replace(/[^0-9]/g, \"\").replace(/(^02|^0505|^1[0-9]{3}|^0[0-9]{2})([0-9]+)?([0-9]{4})/,\"$1-$2-$3\").replace(\"--\", \"-\") );\r\n");
      out.write("        // copy from https://cublip.tistory.com/326\r\n");
      out.write("        //﻿ 원본과 class 명만 바뀐 상태다.\r\n");
      out.write("    });\r\n");
      out.write("</script>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
