/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.50
 * Generated at: 2021-08-19 08:57:30 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.host;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class hostMain_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(10);
    _jspx_dependants.put("/WEB-INF/views/host/../common/hostHeader.jsp", Long.valueOf(1629173518780L));
    _jspx_dependants.put("jar:file:/C:/workspace/ThanksTay/ThanksTay/src/main/webapp/wtpwebapps/ThanksTay/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("jar:file:/C:/workspace/ThanksTay/ThanksTay/src/main/webapp/wtpwebapps/ThanksTay/WEB-INF/lib/spring-webmvc-5.2.16.RELEASE.jar!/META-INF/spring.tld", Long.valueOf(1626216726000L));
    _jspx_dependants.put("jar:file:/C:/workspace/ThanksTay/ThanksTay/src/main/webapp/wtpwebapps/ThanksTay/WEB-INF/lib/spring-webmvc-5.2.16.RELEASE.jar!/META-INF/spring-form.tld", Long.valueOf(1626216726000L));
    _jspx_dependants.put("/WEB-INF/views/host/../common/footer.jsp", Long.valueOf(1627458907962L));
    _jspx_dependants.put("jar:file:/C:/workspace/ThanksTay/ThanksTay/src/main/webapp/wtpwebapps/ThanksTay/WEB-INF/lib/jstl-1.2.jar!/META-INF/fmt.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("/WEB-INF/views/common/tags.jsp", Long.valueOf(1627433983050L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1629344132335L));
    _jspx_dependants.put("jar:file:/C:/workspace/ThanksTay/ThanksTay/src/main/webapp/wtpwebapps/ThanksTay/WEB-INF/lib/jstl-1.2.jar!/META-INF/fn.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("/WEB-INF/lib/spring-webmvc-5.2.16.RELEASE.jar", Long.valueOf(1629348439233L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!doctype html>\r\n");
      out.write("<html lang=\"ko\">\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"utf-8\">\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("<link\r\n");
      out.write("	href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css\"\r\n");
      out.write("	rel=\"stylesheet\">\r\n");
      out.write("<script src=\"https://kit.fontawesome.com/f421352664.js\"\r\n");
      out.write("	crossorigin=\"anonymous\"></script>\r\n");
      out.write("<script\r\n");
      out.write("	src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js\"></script>\r\n");
      out.write("<script\r\n");
      out.write("	src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js\"></script>\r\n");
      out.write("<title>부트스트랩5 템플릿</title>\r\n");
      out.write("<style>\r\n");
      out.write("/* 공통 CSS */\r\n");
      out.write(".container-fluid {\r\n");
      out.write("	padding: 0;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("@import url(http://fonts.googleapis.com/earlyaccess/nanumgothic.css);\r\n");
      out.write("\r\n");
      out.write("body {\r\n");
      out.write("	margin: 0;\r\n");
      out.write("	font-family: 'nanumgothic' !important;\r\n");
      out.write("	font-family: 'Source Sans Pro';\r\n");
      out.write("}\r\n");
      out.write("/* 공통 CSS */\r\n");
      out.write(".enrollButton {\r\n");
      out.write("	margin: 0;\r\n");
      out.write("	align-items: center;\r\n");
      out.write("	font-size: 20px;\r\n");
      out.write("	border-radius: 10px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".reservationWrapperBox {\r\n");
      out.write("	align-items: center;\r\n");
      out.write("	background-image:\r\n");
      out.write("		url('https://a0.muscache.com/im/pictures/cd29ad57-8934-4075-9d5c-6578863fb1dd.jpg?im_w=1920');\r\n");
      out.write("	background-repeat: no-repeat;\r\n");
      out.write("	background-position: center;\r\n");
      out.write("	height: 500px;\r\n");
      out.write("	width: 100%;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".reservationAlarmBox {\r\n");
      out.write("	justify-content: space-between;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".reservationAlarmText {\r\n");
      out.write("	width: 1440px;\r\n");
      out.write("	margin: 0 auto;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".reservationAlarmText p:first-child {\r\n");
      out.write("	font-weight: bold;\r\n");
      out.write("	font-size: 32px;\r\n");
      out.write("	padding-top: 50px;\r\n");
      out.write("	padding-bottom: 0;\r\n");
      out.write("	padding-left: 10%;\r\n");
      out.write("}\r\n");
      out.write("/* 체크 */\r\n");
      out.write(".reservationAlarmText p:nth-child(2) {padding-left 10%;\r\n");
      out.write("	padding-left: 10%;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".todayBox {\r\n");
      out.write("	height: 300px;\r\n");
      out.write("	width: 100%;\r\n");
      out.write("	background-image:\r\n");
      out.write("		url('data:image/webp;base64,UklGRoQCAABXRUJQVlA4WAoAAAAgAAAAHQAAHQAASUNDUAwCAAAAAAIMbGNtcwIQAABtbnRyUkdCIFhZWiAH3AABABkAAwApADlhY3NwQVBQTAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA9tYAAQAAAADTLWxjbXMAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAApkZXNjAAAA/AAAAF5jcHJ0AAABXAAAAAt3dHB0AAABaAAAABRia3B0AAABfAAAABRyWFlaAAABkAAAABRnWFlaAAABpAAAABRiWFlaAAABuAAAABRyVFJDAAABzAAAAEBnVFJDAAABzAAAAEBiVFJDAAABzAAAAEBkZXNjAAAAAAAAAANjMgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAB0ZXh0AAAAAEZCAABYWVogAAAAAAAA9tYAAQAAAADTLVhZWiAAAAAAAAADFgAAAzMAAAKkWFlaIAAAAAAAAG+iAAA49QAAA5BYWVogAAAAAAAAYpkAALeFAAAY2lhZWiAAAAAAAAAkoAAAD4QAALbPY3VydgAAAAAAAAAaAAAAywHJA2MFkghrC/YQPxVRGzQh8SmQMhg7kkYFUXdd7WtwegWJsZp8rGm/fdPD6TD//1ZQOCBSAAAAUAMAnQEqHgAeAD7ZYKpOtiWooygKqsAbCWQAnTLfAiGYXfAA/uw/rDUG/ySry930W5TklUCdPGwZvhShkxmlA5XTMUKtCBVuol3YS6MrvY4AAA==');\r\n");
      out.write("	background-size: cover;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".todayInnerbox {\r\n");
      out.write("	width: 1440px;\r\n");
      out.write("	padding-top: 100px;\r\n");
      out.write("	justify-content: space-between;\r\n");
      out.write("	align-items: center;\r\n");
      out.write("	margin: 0 auto;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".todayTitle {\r\n");
      out.write("	display: flex;\r\n");
      out.write("	font-size: 32px;\r\n");
      out.write("	color: white;\r\n");
      out.write("	align-items: center;\r\n");
      out.write("	justify-content: space-between;\r\n");
      out.write("	padding: 0% 10%;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".todayTitle p {\r\n");
      out.write("	padding-top: 0;\r\n");
      out.write("	margin: 0px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".todayNotice {\r\n");
      out.write("	color: white;\r\n");
      out.write("	padding-top: 20px;\r\n");
      out.write("	padding-left: 10%;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("	<div class=\"container-fluid\">\r\n");
      out.write("		");
      out.write("\r\n");
      out.write("<link\r\n");
      out.write("	href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css\"\r\n");
      out.write("	rel=\"stylesheet\">\r\n");
      out.write("<script\r\n");
      out.write("	src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js\"\r\n");
      out.write("	integrity=\"sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM\"\r\n");
      out.write("	crossorigin=\"anonymous\"></script>\r\n");
      out.write("<script\r\n");
      out.write("	src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js\"></script>\r\n");
      out.write("<script src=\"https://kit.fontawesome.com/f421352664.js\"\r\n");
      out.write("	crossorigin=\"anonymous\"></script>\r\n");
      out.write("<style>\r\n");
      out.write("/* CSS초기화 찾아보기 */\r\n");
      out.write("\r\n");
      out.write("/* hostHeader CSS */\r\n");
      out.write(":root { -\r\n");
      out.write("	-text-color: #f0f4f5; -\r\n");
      out.write("	-background-color: #253343; -\r\n");
      out.write("	-accent-color: #d49466;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("a {\r\n");
      out.write("	margin: 0 auto;\r\n");
      out.write("	text-decoration: none;\r\n");
      out.write("	color: var(- -text-color);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".navbar {\r\n");
      out.write("	display: flex;\r\n");
      out.write("	justify-content: space-between;\r\n");
      out.write("	align-items: center;\r\n");
      out.write("	background-color: #ffffff;\r\n");
      out.write("	padding: 8px 12px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".navbar_logo {\r\n");
      out.write("	display: flex;\r\n");
      out.write("	align-items: center;\r\n");
      out.write("	font-size: 24px;\r\n");
      out.write("	color: white;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".navbar_logo i, a {\r\n");
      out.write("	color: purple;\r\n");
      out.write("	font-weight: bolder;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".navbar_menu {\r\n");
      out.write("	display: flex;\r\n");
      out.write("	list-style: none;\r\n");
      out.write("	margin: 0 auto;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".navbar_menu li {\r\n");
      out.write("	padding: 8px 12px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write(".navbar_icons {\r\n");
      out.write("	list-style: none;\r\n");
      out.write("	color: white;\r\n");
      out.write("	padding-left: 0px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".navbar_icons li {\r\n");
      out.write("	padding: 8px 12px;\r\n");
      out.write("	margin-top: 4px;\r\n");
      out.write("	align-items: center;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".navbar_toggleBtn {\r\n");
      out.write("	display: none;\r\n");
      out.write("	position: absolute;\r\n");
      out.write("	right: 32px;\r\n");
      out.write("	font-size: 24px;\r\n");
      out.write("	color: fuchsia;\r\n");
      out.write("}\r\n");
      out.write("/* 미디어 쿼리  */\r\n");
      out.write("@media screen and (max-width: 768px) {\r\n");
      out.write("	.navbar {\r\n");
      out.write("		flex-direction: column;\r\n");
      out.write("		align-items: flex-start;\r\n");
      out.write("		padding: 8px, 24px;\r\n");
      out.write("		position: relative;\r\n");
      out.write("	}\r\n");
      out.write("	.navbar_logo {\r\n");
      out.write("		display: flex;\r\n");
      out.write("		align-items: center;\r\n");
      out.write("		font-size: 24px;\r\n");
      out.write("		color: white;\r\n");
      out.write("	}\r\n");
      out.write("	.navbar_menu {\r\n");
      out.write("		display: none;\r\n");
      out.write("		flex-direction: column;\r\n");
      out.write("		align-items: center;\r\n");
      out.write("		width: 100%;\r\n");
      out.write("	}\r\n");
      out.write("	.navbar_menu li {\r\n");
      out.write("		width: 100%;\r\n");
      out.write("		text-align: center;\r\n");
      out.write("	}\r\n");
      out.write("	.navbar_icons {\r\n");
      out.write("		display: none;\r\n");
      out.write("		justify-content: center;\r\n");
      out.write("		width: 100%;\r\n");
      out.write("	}\r\n");
      out.write("	.navbar_toggleBtn {\r\n");
      out.write("		display: block;\r\n");
      out.write("	}\r\n");
      out.write("	.navbar_menu.active, .navbar_icons.active {\r\n");
      out.write("		display: flex;\r\n");
      out.write("	}\r\n");
      out.write("}\r\n");
      out.write("/* hostHeader CSS */\r\n");
      out.write(".btn-secondary{\r\n");
      out.write("	color: purple;\r\n");
      out.write("	font-weight:bold;\r\n");
      out.write("	border: none;\r\n");
      out.write("	background-color:white;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("<script src=\"https://kit.fontawesome.com/f421352664.js\"\r\n");
      out.write("	crossorigin=\"anonymous\"></script>\r\n");
      out.write("<header>\r\n");
      out.write("	<nav class=\"navbar\">\r\n");
      out.write("		<div class=\"navbar_logo\">\r\n");
      out.write("			<a href=\"home\"><i class=\"fab fa-airbnb\"></i></a>\r\n");
      out.write("		</div>\r\n");
      out.write("		<ul class=\"navbar_menu\">\r\n");
      out.write("			<li><a href=\"\">투데이</a></li>\r\n");
      out.write("			<li><a href=\"\">메시지</a></li>\r\n");
      out.write("			<li><a href=\"\">달력</a></li>\r\n");
      out.write("			<li><a href=\"/host/earnings\">인사이트</a></li>\r\n");
      out.write("			<div class=\"dropdown\">\r\n");
      out.write("				<button class=\"btn btn-secondary dropdown-toggle\" type=\"button\"\r\n");
      out.write("					id=\"dropdownMenuButton2\" data-bs-toggle=\"dropdown\"\r\n");
      out.write("					aria-expanded=\"false\">메뉴</button>\r\n");
      out.write("				<ul class=\"dropdown-menu\" aria-labelledby=\"dropdownMenuButton2\">\r\n");
      out.write("					<li><a class=\"dropdown-item\" href=\"/host/filtering\" style=\"z-index: 10\">숙소</a></li>\r\n");
      out.write("					<li><a class=\"dropdown-item\" href=\"/host/transactionhome\" style=\"z-index: 10\">대금수령내역</a></li>\r\n");
      out.write("					<li><a class=\"dropdown-item\" href=\"#\" style=\"z-index: 10\">숙소등록하기</a></li>\r\n");
      out.write("				</ul>\r\n");
      out.write("			</div>\r\n");
      out.write("		</ul>\r\n");
      out.write("		<div class=\"navbar_icons\">\r\n");
      out.write("			<a href=\"\"><i class=\"fas fa-user-alt\"></i></a>\r\n");
      out.write("		</div>\r\n");
      out.write("		<a href=\"#\" class=\"navbar_toggleBtn\"> <i class=\"fas fa-bars\"\r\n");
      out.write("			style=\"display: block;\"></i>\r\n");
      out.write("		</a>\r\n");
      out.write("	</nav>\r\n");
      out.write("\r\n");
      out.write("</header>\r\n");
      out.write("\r\n");
      out.write("		<section>\r\n");
      out.write("			<div class=\"todayBox\">\r\n");
      out.write("				<div class=\"todayInnerbox\">\r\n");
      out.write("					<div class=\"todayTitle\">\r\n");
      out.write("						<p>투데이</p>\r\n");
      out.write("						<span><a href=\"lodgingRegister\"><button\r\n");
      out.write("									class=\"enrollButton\">새 숙소 등록하기</button></a></span>\r\n");
      out.write("					</div>\r\n");
      out.write("					<div class=\"todayNotice\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${loginedUser.name }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("님 지금 바로 에어비앤비의 호스트가 되어 보세요!</div>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("			<div class=\"reservationWrapperBox\">\r\n");
      out.write("				<div class=\"reservationAlarmBox\"></div>\r\n");
      out.write("				<div class=\"reservationAlarmText\">\r\n");
      out.write("					<p>예약</p>\r\n");
      out.write("					<p>게스트가 숙소를 예약하면 여기에 표시됩니다.</p>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</section>\r\n");
      out.write("	");
      out.write("\r\n");
      out.write("<style>\r\n");
      out.write("#footer{\r\n");
      out.write("	background-color: #F7F7F7 !important;\r\n");
      out.write("    border-top: 1px solid #DDDDDD !important;\r\n");
      out.write("    padding-top: 40px;\r\n");
      out.write("    padding-bottom: 40px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#footer li{\r\n");
      out.write("	list-style : none;\r\n");
      out.write("	margin-bottom : 15px;\r\n");
      out.write("	font-size: 15px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#footer .box-upper{\r\n");
      out.write("    padding-bottom: 20px !important;\r\n");
      out.write("}\r\n");
      out.write("#footer .box-lower{\r\n");
      out.write("    padding-top: 40px !important;\r\n");
      out.write("    border-top: 1px solid #DDDDDD !important;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("<div id=\"footer\">\r\n");
      out.write("	<div class=\"container\">\r\n");
      out.write("		<div class=\"box-upper\">\r\n");
      out.write("			<div class=\"row\">\r\n");
      out.write("				<div class=\"col-3\">\r\n");
      out.write("					<ul class=\"list-group\">\r\n");
      out.write("						<li><strong>소개</strong></li>\r\n");
      out.write("						<li><a>에어비앤비 이용 방법</a></li>\r\n");
      out.write("						<li>뉴스룸</li>\r\n");
      out.write("						<li>에어비앤비 2021</li>\r\n");
      out.write("						<li>투자자 정보</li>\r\n");
      out.write("						<li>에어비앤비 플러스</li>\r\n");
      out.write("						<li>에어비앤비 Luxe</li>\r\n");
      out.write("						<li>호텔투나잇</li>\r\n");
      out.write("						<li>에어비앤비 비즈니스 프로그램</li>\r\n");
      out.write("						<li>호스트 분들이 있기에 가능합니다</li>\r\n");
      out.write("						<li>채용정보</li>\r\n");
      out.write("						<li>창립자 편지</li>\r\n");
      out.write("					</ul>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"col-3\">\r\n");
      out.write("					<ul class=\"list-group\">\r\n");
      out.write("						<li><strong>커뮤니티</strong></li>\r\n");
      out.write("						<li>다양성 및 소속감</li>\r\n");
      out.write("						<li>접근성</li>\r\n");
      out.write("						<li>에어비앤비 어소시에이트</li>\r\n");
      out.write("						<li>구호 인력을 위한 숙소</li>\r\n");
      out.write("						<li>게스트 추천</li>\r\n");
      out.write("						<li>Airbnb.org</li>\r\n");
      out.write("					</ul>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"col-3\">\r\n");
      out.write("					<ul class=\"list-group\">\r\n");
      out.write("						<li><strong>호스팅하기</strong></li>\r\n");
      out.write("						<li>숙소 호스팅</li>\r\n");
      out.write("						<li>온라인 체험 호스팅하기</li>\r\n");
      out.write("						<li>체험 호스팅하기</li>\r\n");
      out.write("						<li>책임감 있는 호스팅</li>\r\n");
      out.write("						<li>호스트 추천</li>\r\n");
      out.write("						<li>자료 센터</li>\r\n");
      out.write("						<li>커뮤니티 센터</li>\r\n");
      out.write("					</ul>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"col-3\">\r\n");
      out.write("					<ul class=\"list-group\">\r\n");
      out.write("						<li><strong>에어비앤비 지원</strong></li>\r\n");
      out.write("						<li>에어비앤비의 코로나19 대응 방안</li>\r\n");
      out.write("						<li>도움말 센터</li>\r\n");
      out.write("						<li>예약 취소 옵션</li>\r\n");
      out.write("						<li>신뢰와 안전</li>\r\n");
      out.write("					</ul>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>	\r\n");
      out.write("		<div class=\"box-lower\">\r\n");
      out.write("			<div class=\"row\">\r\n");
      out.write("				<div class=\"col-6\">\r\n");
      out.write("					© 2021 Airbnb, Inc.<br/>\r\n");
      out.write("					개인정보 처리방침·이용약관·사이트맵·한국의 변경된 환불 정책·회사 세부정보\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"col-3\">\r\n");
      out.write("					<p>한국어 (KR) $ SGD</p>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"col-3\">\r\n");
      out.write("					A\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("</div>");
      out.write("\r\n");
      out.write("	</div>\r\n");
      out.write("	<script src=\"https://kit.fontawesome.com/f421352664.js\"\r\n");
      out.write("		crossorigin=\"anonymous\"></script>\r\n");
      out.write("	<script\r\n");
      out.write("		src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js\"></script>\r\n");
      out.write("	<script\r\n");
      out.write("		src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js\"></script>\r\n");
      out.write("	<script>\r\n");
      out.write("		/* hostHeader JS */\r\n");
      out.write("		\r\n");
      out.write("		const toggleBtn = document.querySelector(\".navbar_toggleBtn\");\r\n");
      out.write("		const menu = document.querySelector('.navbar_menu');\r\n");
      out.write("		const icons = document.querySelector('.navbar_icons');\r\n");
      out.write("\r\n");
      out.write("		toggleBtn.addEventListener('click', function() {\r\n");
      out.write("			menu.classList.toggle('active');\r\n");
      out.write("			icons.classList.toggle('active');\r\n");
      out.write("		});\r\n");
      out.write("	</script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
